gamer_community:
  links:
    gravatar: https://secure.gravatar.com/avatar/
  help:
    mail: mailto:xiangxiang181818@gmail.com

validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6

collections:
  session_controller_create: 1

users:
  image:
    height: 100
    width: 100
  default_image:
    list: 50
  icon: 30

posts:
  page:
    max: 5
