gamer_community:
  links:
    gravatar: https://secure.gravatar.com/avatar/
  help:
    mail: mailto:xiangxiang181818@gmail.com

validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6

collections:
  session_controller_create: 1
  ps_reset_expired_time_in_hours: 2

users:
  image:
    height: 100
    width: 100
  default_image:
    list: 50
  icon: 30
  page:
    default_page: 10

posts:
  page:
    max: 5
  view:
    inc: 1

blob:
  image:
    min_length: 800
    min_width: 600
    max_length: 1024
    max_width: 768

conversation:
  truncate:
    length: 145

notification:
  default_page: 8
activities:
  per_page_10: 10

games:
  images:
    dota:
      width: 265
      height: 160
    genshin:
      width: 265
      height: 170
    fortnite:
      width: 265
      height: 160
    gta:
      width: 265
      height: 170
    pubg:
      width: 265
      height: 170
    CSGo:
      width: 265
      height: 150
    slamdunk:
      width: 265
      heigth: 195
    falcom:
      width: 265
      height: 130
  links:
    dota: https://www.dota2.com/play/
    genshin: https://genshin.mihoyo.com/en
    fortnite: https://www.epicgames.com/fortnite/en-US/home
    pubg: https://www.pubg.com/en-us/
    CSGo: https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/
    slamdunk: https://slamdunkmobile.com/
    gta: https://www.rockstargames.com/
    falcom: https://www.falcom.co.jp/hajimari/
